services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste-app
    ports:
      - "5049:5049"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CAPTCHA_API_KEY=${CAPTCHA_API_KEY}
      - HEADLESS=${HEADLESS:-false}
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
